### ISSUE TITLE
StaticSysTopo.dat missing

### ISSUE THREAD

**Issue by vicdoval** [DMST1990/ToOptiX#1]
Hello, thanks for sharing your research, great material. I'm trying to use your add-on in blender, i have tried several versions but it seems to miss something, im trying with your file  InputS.inp Bender 2.78c in Windows / and freeCad 016 (for the ccx)

I paste here the error:

Traceback (most recent call last):
  File "C:\....\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\ui_topo.py", line 86, in execute
    TopologyConfig.run_optimization(volfrac, penal, workDir, solverPath, matSets, iterations, StructIsActive, staticPath, weightStatic, thermIsActive, heatPath, no_design_path, no_design_active, weightTherm)
  File "C:\....\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\TopologyConfig.py", line 121, in run_optimization
    result_reader.add_displacement(femObj_topo)
  File "C:\.....\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\Phraser.py", line 804, in add_displacement
    i_file = open(self.__filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\working directory\\strutureOp\\New Folder(1)\\StaticSysTopo.dat'

location: <unknown location>:-1

Any idea?

Anyway, Thanks and congratulations!

**Comment by DMST1990** [comment]
Hi, 
thank you for reporting this bug :).
Big sorry for this stupid programming mistake.
Goto the end of the file "InputS.inp" and add a new empty line

**Your case** 
#--------------
*Dsload
_Surf-1_S5, P5, 1000.
_Surf-1_S3, P3, 1000.
_Surf-1_S6, P6, 1000.
*End Step
#------End of file--------


Just paste a new empty line into the file end so that it should look like 

**How it should look like**
#--------------
.......
*Dsload
_Surf-1_S5, P5, 1000.
_Surf-1_S3, P3, 1000.
_Surf-1_S6, P6, 1000.
*End Step

#--- End of file-----------

I will fix this one in the next version :)

**Comment by DMST1990** [comment]
I uploaded a new "InputS.inp" file.
This one should work (Just one line added)

**Comment by vicdoval** [comment]
Thanks for your answer, 
but i still get the same error about StaticSysTopo.dat'

**Comment by DMST1990** [comment]
Can you send me the "StaticSysTopo.inp" file.
Then i will check what went wrong.
ToOptix_04_2017_new.tar.gz <--- this is the latest version.


I get the same problem if i run this example in a server (E:) on which my rights are limeted.
There the file "StaticSysTopo.inp" can`t be created, which is nessecarry for the Solver run.
Try to create a working folder on the desktop. There you should have all rights as the user.

I will make a new tutorial on youtube. There i will show you how you can run this on a windows example and how can you check on problems.

**Comment by vicdoval** [comment]
I used de 04_2017_new on the desktop but with no results,  

The file you asked for [StaticSysTopo.inp](https://drive.google.com/open?id=0B1poCxzLyT2gbmp2YlhCOGhxeTg)

**Comment by DMST1990** [comment]
This file worked quiete well (how it should be).
I found this windows sepcific problem.

The solver call doesn`t work. Spaces in the folder should be avoided :).

**Good**
C:\FreeCAD\bin\ccx.exe

**Bad**
C:\Program Files\FreeCAD 0.16\bin\ccx.exe

I would suggest just paste the files into your working folder, which are loacated in FreeCAD\bin\

ccx.exe
pthreadGC2-w64.dll
pthreadVC2.dll

**Comment by vicdoval** [comment]
I did as you suggested,  now StaticSysTopo.dat its created  but i get this error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\ui_topo.py", line 86, in execute
    TopologyConfig.run_optimization(volfrac, penal, workDir, solverPath, matSets, iterations, StructIsActive, staticPath, weightStatic, thermIsActive, heatPath, no_design_path, no_design_active, weightTherm)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\TopologyConfig.py", line 131, in run_optimization
    optimizer.set_sensitivity_as_energy_density(design_space, system)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\ToOptix\TopologyOptimization.py", line 303, in set_sensitivity_as_energy_density
    median = np.median(new_sens)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\site-packages\numpy\lib\function_base.py", line 3084, in median
    overwrite_input=overwrite_input)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\site-packages\numpy\lib\function_base.py", line 2997, in _ureduce
    r = func(a, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\site-packages\numpy\lib\function_base.py", line 3117, in _median
    part = partition(a, kth, axis=axis)
  File "C:\Program Files\Blender Foundation\Blender\2.78\python\lib\site-packages\numpy\core\fromnumeric.py", line 638, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)
TypeError: unorderable types: NoneType() > NoneType()

location: <unknown location>:-1

**Comment by DMST1990** [comment]
Can you send me the File "StaticSysTopo.dat" and "StaticSensTopo.inp"
then i can check what went wrong.

**Comment by vicdoval** [comment]
This are the files:
[StaticSensTopo.dat](https://drive.google.com/open?id=0B1poCxzLyT2gN0t2UlpZSS1lRGc)
[StaticSysTopo.dat](https://drive.google.com/open?id=0B1poCxzLyT2gbmp2YlhCOGhxeTg)

**Comment by DMST1990** [comment]
I know whats the problem. (It`s windows specific)
This takes me until thursday for fixing it. 
Thanks for your help and sorry for the errors.

**Comment by NickTOP8** [comment]
Hi Martin,

Thank you for sharing your work with the community. I watched your YouTube videos and followed the steps described there (for an older version). 

However, I have the same issues described above and I would like to know if these were resolved. 

The first issue: FileNotFoundError: [Errno 2] No such file or directory: '……\StaticSysTopo.dat'
was corrected by your sugestion of not including white spaces in the folder names of ccx.exe

Good
C:\FreeCAD\bin\ccx.exe
Bad
C:\Program Files\FreeCAD 0.16\bin\ccx.exe

However the second issue "TypeError: unorderable types: NoneType() > NoneType()" is still present. 
It seems that both set_sensitivity_as_... functions include objects that are not comparable. 

You write above that this is a windows specific issue. Do you mean Windows version? I tried both Windows 7 and Windows 10 and they both have the same error. 

Can you please tell me, what Windows do you have? Also, can you please post the older version on ToOptix you show in the YouTube video. 

Any suggestion for solving this problem? 

Your help is much appreciated
Regards
Nick

**Comment by DMST1990** [comment]
Hi Nick,

you need just to install blender and FreeCAD in a user folder like the desktop or documents.
Then it should work.

I cant change this fact because a ussage between two different folder in the "Programms" of windows needs admi. rights.

So in this case "ccx.exe" couldn`t be startet.

Best Regards

Martin

**Comment by NickTOP8** [comment]
Hi Martin,

Thank you for your prompt reply. Installing both Blender and FreeCAD in a folder on my desktop solved the problem. I tested your examples and they work fine.

I will create an example from scratch (as you show in the youtube video) and run it using your code.

Great work! 
Sincerely, 
Nick
