### ISSUE TITLE
which folder

### ISSUE THREAD

**Issue by lukeskymuh** [DMST1990/ToOptiX#3]
Hi,

I admire your amazing work and would like to test it. Unfortunatly it is not clear which of the may folders is currently the Blender plug in to be copied.
It would be great if you add a github link on your youtube videos. I dont know why the github search function returned no results.

Best Regards
Luke

**Comment by DMST1990** [comment]
HI Luke,

sorry for the late response (i am working on my master theses right now).

Ill created a description

https://github.com/DMST1990/ToOptixUpdate

Best Regards,

Martin
