### ISSUE TITLE
ToOptix_23_04_2018 FoundNotFoundError U_system_optimization.frd

### ISSUE THREAD

**Issue by mmncd** [DMST1990/ToOptiX#4]
I have installed Blender and FreeCAD without administration permission. Within Blender I have installed and set the last version of ToOptix that is 23_04_2018.
When I started Blender I have configured it within the tab ToOptix:
   - I have chosen the ccx.exe solver from FreeCAD.
   - I have chosen an empty folder for the result folder.
   - I have chosen TwoRectanglesStruc.inp path for the static physic and TwoRectanglesThem.inp for the Heat transfer.
   - Then I press Start optimization button, and it throws the following exception:
Report: Error
Traceback (most recent call last):
   File "C:\Users\myusername\Desktop\myproject\Blender\2.7.9\scripts\addons\ToOptix\ui_topo.py", line 94, in execute files, workDir, solverPath, cpus)
   File "C:\Users\myusername\Desktop\myproject\Blender\2.7.9\scripts\addons\ToOptix\run_optimization.py", line 25, in run_optimization opti_controller.run()
   File "C:\Users\myusername\Desktop\myproject\Blender\2.7.9\scripts\addons\ToOptix\TopologyOptimizer\OptimizationController.py", line 82, in run self.__optimization(file, fem_body, ele_filter, solution_type)
   File "C:\Users\myusername\Desktop\myproject\Blender\2.7.9\scripts\addons\ToOptix\TopologyOptimizer\OptimizationController.py", line 131, in __optimization frd_reader.get_displacement(fem_body.get_nodes())
   File "C:\Users\myusername\Desktop\myproject\Blender\2.7.9\scripts\addons\ToOptix\TopologyOptimizer\FEMPy\CCXPhraser.py", line 195, in get_displacement frd_file = open(self.__file_name, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\myusername\\Desktop\\myproject\\myresultsfolder\\U_system_optimization.frd'
location: <unknown location>:-1

What am I missing?

**Comment by mmncd** [comment]
What am I missing?

**Comment by DMST1990** [comment]
Hello,
in this Case the finite element calculation failed. 
There can be several different options.

0. First check if you can use the example files (They should work) "TwoRectanglesStruc.inp", "TwoRectanglesTherm.inp"
a) If they work then go to point 4
b) If not then do 1-3

1. Some model defintions in the input file are wrong.
a) Try to run in the command prompt:  ccx.exe "inputfilename"

2. If you use the blender extension/add on, 
a) you should create a copy of blender in a user folder (so Administrator-rights are not needed).
b) you can run blender in administrator-mode, so there shouldn`t be something wrong with the user rights.

3. The same as in 2 but with FreeCAD (ccx)


4. There could be a bug in the code 
a) You can send me the file.inp and i can run it on my machine

Best Regards Martin

**Comment by mmncd** [comment]
Thanks for your response. 

As I said, I have installed the program without administration rights and I have chosen TwoRectanglesStruc.inp for the static physic and TwoRectanglesTherm.inp for the Heat transfer. 

At the end, I have solved the problem by changing the solver. I have used the solver of Calculix instead of FreeCAD. 

The result was 40 files:
   - 10 files with the pattern 0stl_result0.******************.stl
   - 10 files with the pattern 1stl_result0.******************.stl
   - ENER_sensitivity_optimization.cvg
   - ENER_sensitivity_optimization.dat
   - ENER_sensitivity_optimization.frd
   - ENER_sensitivity_optimzation.inp
   - ENER_sensitivity_optimization.sta
   - HFL_sensitivity_optimization.cvg
   - HFL_sensitivity_optimization.dat
   - HFL_sensitivity_optimization.frd
   - HFL_sensitivity_optimization.inp
   - HFL_sensitivity_optimization.sta
   - NT_sensitivity_optimization.cvg
   - NT_sensitivity_optimization.dat
   - NT_sensitivity_optimization.frd
   - NT_sensitivity_optimization.inp
   - NT_sensitivity_optimization.sta
   - U_system_optimization.cvg
   - U_system_optimization.dat
   - U_system_optimization.frd
   - U_system_optimization.inp
   - U_system_optimization.sta

What is the meaning of each file?

Best regards,
María
