### ISSUE TITLE
Linebreak recognition / Running without blender

### ISSUE THREAD

**Issue by prosimas** [DMST1990/ToOptiX#5]
Hi Martin,

I noticed an issue with line breaks while running without blender. Error occurs in to parsing process of inp file: when there is a linebreak after (here marked with \n)

*ELASTIC
2300, 0.395\n

the conversion of string to float fails in CCXPhraser, line 157.

Can you confirm this issue?

Best wishes
prosimas

**Comment by DMST1990** [comment]
Hi Prosimas,

i fixed it.
Thank you very much for the report.

Best wishes 

Martin
