### ISSUE TITLE
CCX Phraser issue / Running without blender

### ISSUE THREAD

**Issue by prosimas** [DMST1990/ToOptiX#6]
Hi Martin, 

an error occurs while parsing inp file. I am executing toOptix without blender. Material assignment from input file is not recognized. For all elements CalculiX displays 

*ERROR in calinput: no material was assigned to element ...

After that, toOptix fails with

FileNotFoundError: [Errno 2] No such file or directory: './U_system_optimization.frd'

Sample input file is attached. 

[Analysis.txt](https://github.com/DMST1990/ToOptiX/files/2038664/Analysis.txt)

Best wishes
prosimas

**Comment by prosimas** [comment]
I'm wondering: are second order elements supported? I'm using C3D10 elements.

**Comment by prosimas** [comment]
Ok, the reason for this issue is the mesh import at the beginning of the posted input file. ToOptix is not able to handle the include card correctly.

**Comment by DMST1990** [comment]
Hello Prosimas,

allright, i fixed the material problem and the element type problem.
There are 4 files (tetrahedral, hexahedral with different oders.

https://github.com/DMST1990/ToOptixUpdate/ToOptix_25_05_2018.zip

So i hope you can go furhter now.

Best wishes

Martin

**Comment by DMST1990** [comment]
Hello Prosimas,

Oh yeah, thats the case "includes wont work".
I can extend it at the weekend. So it will work with includes

(Hexahedral with second order are working now aswell)

Best wishes


Martin

**Comment by prosimas** [comment]
Hi Martin,

wow that was fast! 👍 Thank you very much for your help and time! I will try the new version as soon as possible.

Great project!
