### ISSUE TITLE
Definition of fix sets?

### ISSUE THREAD

**Issue by prosimas** [DMST1990/ToOptiX#8]
Hi Martin,

I wonder: is it possible to define fix sets in ToOptix? I mean sets of elements which should not be touched by the optimization? 

Best wishes
prosimas

**Comment by DMST1990** [comment]
Hi prosimas,

i ll write an extension. Give me some time :).


Best wishes

Martin

**Comment by DMST1990** [comment]
Hi prosimas,

i have written an extension (not supported by using the blender extension).
You need to create a extra file with a elementset (a name is not nessecarry).
"no_design_space.inp" with

*ELSET,
1,2,3,4,5,6
7,8,9,10,11,12



```python,example

from run_optimization import run_optimization

cpus = 4
opti_type = "seperated"
# no design space is used until redefinition
sol_type = ["no_design_space", "static"]
files = ["no_design_space.inp", "TwoRectanglesStruc.inp"]
max_iteration = 20
vol_frac = 0.3
penal = 3.0
matSets = 10
weight_factors = [3.0]
workDir = "work"
solverPath = "ccx"
run_optimization(penal,  matSets, opti_type, sol_type,
                                      weight_factors, max_iteration, vol_frac,
                                      files, workDir, solverPath, cpus)

```

Best Wishes

Martin

**Comment by prosimas** [comment]
Hi Martin! You are great 👍 I'll test it and give you feedback as soon as possible!

**Comment by prosimas** [comment]
It seems to work well on a test case👍 although I have no reference to validate the results with other solvers. I tried to validate with z88Arion, but up to now the mesh import in z88 was not successful.

**Comment by DMST1990** [comment]
Hello Prosimas,

you only need to import and re-export the file in Blender (Then the missing STL part is extended by blender)
Another possible method is import the STL-File in FreeCAD.

Best wishes 

Martin
